version: "3.9"

services:
  local-db:
    image: postgres:15.1-alpine3.17
    container_name: johnjud-local-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: johnjud_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - johnjud

  file:
    container_name: johnjud-file
    restart: unless-stopped
    build: .
    ports:
      - 3004:3004
    environment:
      APP_PORT: 3004
      APP_ENV: production
      DB_URL: postgres://root:root@johnjud-local-db:5432/johnjud_db
      BUCKET_ENDPOINT: BUCKET_ENDPOINT
      BUCKET_ACCESS_KEY: BUCKET_ACCESS_KEY
      BUCKET_SECRET_KEY: BUCKET_SECRET_KEY
      BUCKET_NAME: johnjud-pet-images
      BUCKET_USE_SSL: false
    networks:
      - johnjud

volumes:
  postgres:
networks:
  johnjud:
