app:
  port: 3004
  debug: true

database:
  host: localhost
  port: 5432
  name: johnjud_db
  username: root
  password: root

bucket:
  endpoint: <endpoint>
  access_key_id: <access_key_id>
  secret_access_key: <secret_access_key>
  use_ssl: false
  bucket_name: <bucket name>
